#!/bin/sh

# Define directory variables.

TARGET_DIR="$3"
PKG_DIR="$1/Contents/Resources"
SCRIPTS_DIR="$TARGET_DIR/Library/Scripts/Managed"
LAUNCHD_DIR="$TARGET_DIR/Library/LaunchDaemons"
LocalMCX_DB="$TARGET_DIR/var/db/dslocal/nodes/MCX"

# Create Local MCX
add_local_mcx() {
	echo "Creating LocalMCX DB at $LocalMCX_DB"
	/bin/mkdir "$LocalMCX_DB"
	/usr/sbin/chown -R 0:0 "$LocalMCX_DB"
	/bin/chmod 700 "$LocalMCX_DB"
}

# first make sure /Local/MCX node exists, otherwise create it
if [ ! -d "${LocalMCX_DB}" ] ; then
	echo "Missing /Local/MCX node!"
	add_local_mcx
fi

# If scripts subfolder doesn't exist, create it
if [ ! -d "${SCRIPTS_DIR}" ] ; then
	echo "Missing $SCRIPTS_DIR...creating"
	/bin/mkdir "$SCRIPTS_DIR"
fi

# get our launchd job loaded into the right directories
cp -v "${PKG_DIR}/com.afp548.LocalMCX-fixSearchPath.plist" $LAUNCHD_DIR
cp -v "${PKG_DIR}/LocalMCX-fixSearchPath.sh" $SCRIPTS_DIR
cp -v "${PKG_DIR}/com.afp548.localMCX-fixMACaddy.plist" $LAUNCHD_DIR
cp -v "${PKG_DIR}/fixComputerRecord.sh" $SCRIPTS_DIR
cp -v "${PKG_DIR}/com.afp548.networkingUp.plist" "$TARGET_DIR/Library/LaunchAgents"
cp -v "${PKG_DIR}/networkCheckers.py" $SCRIPTS_DIR

# move all of our management policies and associated records into the right places
ditto -V "${PKG_DIR}/computergroups" "${LocalMCX_DB}/computergroups"
ditto -V "${PKG_DIR}/computers" "${LocalMCX_DB}/computers"

exit 0
